version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shopychange
    volumes:
      - ./databases/mongodb:/databases/mongodb/db
    ports:
      - 27017:27017
