export const colors = {
  primaryChakraColor: 'blue',
  primaryShadowColor: '#89CFF0',
  primaryTransparent: '#89CFF055',
  buyChakraColor: 'blue',
  buyShadowColor: '#89CFF0',
  approveChakraColor: 'blue',
  approveShadowColor: '#89CFF0',
  modifyChakraColor: 'blue',
  modifyShadowColor: '#89CFF0',
  sellChakraColor: 'green',
  sellShadowColor: '#80FFA8',
  forSaleChakraColor: 'orange',
  forSaleShadowColor: '#FA9C1B',
  cancelChakraColor: 'gray',
  cancelShadowColor: '#696969',
  blueChakraColor: 'blue',
  blueShadowColor: '#89CFF0',
  popover: {
    bgChakraColor: 'blue',
    textChakraColor: 'blue',
  },
  loadingChakraColor: 'gray',
}
