# Generated by Django 4.1.9 on 2023-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(to='blockchainAPI.nftcollection'),
        ),
    ]
