# Generated by Django 4.1.9 on 2023-08-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainAPI', '0002_user_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collections',
        ),
        migrations.DeleteModel(
            name='NFTCollection',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
